// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebProject.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Project.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "yousef",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ali",
                            Password = "234"
                        },
                        new
                        {
                            Id = 3,
                            Name = "hi",
                            Password = "345"
                        });
                });

            modelBuilder.Entity("Web_Project.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("GameStateId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("releaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("GameStateId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GameStateId = 1,
                            PlatformId = 1,
                            name = "Overwatch",
                            releaseDate = "12/2",
                            src = "https://blz-contentstack-images.akamaized.net/v3/assets/blta8f9a8e092360c6c/bltdf9dd58b1d2893d5/6324a79fe337fa0dc7263db4/overwatch2.jpg?format=webply&quality=80&auto=webp"
                        },
                        new
                        {
                            GameId = 2,
                            GameStateId = 2,
                            PlatformId = 2,
                            name = "Overwatch",
                            releaseDate = "12/2",
                            src = "https://blz-contentstack-images.akamaized.net/v3/assets/blta8f9a8e092360c6c/bltdf9dd58b1d2893d5/6324a79fe337fa0dc7263db4/overwatch2.jpg?format=webply&quality=80&auto=webp"
                        },
                        new
                        {
                            GameId = 3,
                            GameStateId = 3,
                            PlatformId = 3,
                            name = "Overwatch",
                            releaseDate = "12/2",
                            src = "https://blz-contentstack-images.akamaized.net/v3/assets/blta8f9a8e092360c6c/bltdf9dd58b1d2893d5/6324a79fe337fa0dc7263db4/overwatch2.jpg?format=webply&quality=80&auto=webp"
                        },
                        new
                        {
                            GameId = 4,
                            GameStateId = 3,
                            PlatformId = 1,
                            name = "Heroes of the storm",
                            releaseDate = "12/2",
                            src = "https://blz-contentstack-images.akamaized.net/v3/assets/blta8f9a8e092360c6c/bltce07525c7490946d/61a50fc22e73ff101cdc1c8d/heroes.jpg?format=webply&quality=80&auto=webp"
                        },
                        new
                        {
                            GameId = 5,
                            GameStateId = 2,
                            PlatformId = 2,
                            name = "Starcraft II",
                            releaseDate = "12/2",
                            src = "https://blz-contentstack-images.akamaized.net/v3/assets/blta8f9a8e092360c6c/blt3873027b9450f357/61a50f033c4e21100a80f1fc/starcraft2.jpg?format=webply&quality=80&auto=webp"
                        });
                });

            modelBuilder.Entity("Web_Project.Models.GameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("gameStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Released"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EarlyAccess"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Upcoming"
                        });
                });

            modelBuilder.Entity("Web_Project.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pc"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Console"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Playstation"
                        });
                });

            modelBuilder.Entity("Web_Project.Models.Game", b =>
                {
                    b.HasOne("Web_Project.Models.GameState", "GameState")
                        .WithMany("Games")
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Project.Models.Platform", "Platform")
                        .WithMany("Games")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameState");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Web_Project.Models.GameState", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Web_Project.Models.Platform", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
